### ISSUE TITLE
developer instructions?

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#104] opened 2016-09-05 20:54 UTC
Hi, I would like to possibly contribute to this project.  I wonder if you could document how you work on it.  The Readme just talks about downloading the pre-build executables.  I tried just running "ant", which gave a helpful message, and then (since I'm currently running on Windows), I tried "ant dist.win".

This gave an error that launch4j was not found.

I'm sure I could download launch4j and keep plugging away, but really I don't want to have to "wrap" the application, if possible.  I assume you don't regularly do so for development.  Again, while I'm sure I could figure something out, it would be nice to know what you do.

**Comment by daveharris** [comment] 2016-09-05 22:24
Hi John,

Thanks for getting in touch, we'd love to have you on board.

There is some sketchy documentation [on the Development Setup wiki page](https://github.com/tvrenamer/tvrenamer/wiki/Development-Setup). However, I note that `launch4j` is not listed there anywhere ... oops!

I'm pretty sure that `launch4j` is the only external build dependency. It should just be a matter of:

1. [Downloading launch4j](https://sourceforge.net/projects/launch4j/files/launch4j-3/3.9/). Extract it somewhere
1. Copy `build.properties.template` to `build.properties` and set the `launch4j.path` attribute to where you extracted launch4j to above
1. Run `ant dist.win`

If you could check that those steps are correct, I will update the wiki with the information for other people.

I note that we have included the `appbundler-1.0ea.jar` file directly in the repository for making OSX applications so maybe we should be doing the same for Launch4j ...

Let me know how it goes. Happy to help out if things don't go smoothly.

Dave

**Comment by daveharris** [comment] 2016-09-05 22:28
Hi John,

Sorry it seems that I totally mis-read your request. I thought you were trying to build it, not run it...

How we do this is just use Eclipse to run the application for us. It should just be a matter of adding the SWT library for your Operating System and architecture and configuring `src/main` as a source folder. Then running the `UIStarter` class will fire up the application

Dave

**Comment by johnv02139** [comment] 2016-09-06 00:04
Thanks for the speedy response!  I really wasn't sure how active your project was, so in addition to being helpful, it's reassuring!

I started writing Java code when Java was brand new, and very little tooling was available.  I'm trying to catch up :) but I'm still accustomed to manually constructing a classpath and running Java directly.  I tried early versions of Eclipse, and was not impressed, but I'm sure it's light years better now.  I may try it again.  In the mean time, my low-level history helped me write a little script that allowed me to run it.

Basically after doing "ant compile", all I needed to do was copy the version file into the out directory, and add the libraries to the classpath, and it runs just fine.

Sorry I didn't notice the Wiki section.

I think the first thing I'm interested in working on is allowing multiple selection.  It's as simple as adding SWT.MULTI to the Table constructor to get the widget to allow multiple rows to be selected, but it doesn't work as expected.  Toggling the check box of a line still affects only that line, even if multiple lines are selected.  So I'm going to see if I can get it to behave as I would expect.

If you have any insight into this, or history, or are just opposed to it, please let me know.  :)

**Comment by daveharris** [comment] 2016-09-06 00:37
Hi,

The project has certainly stagnated. it was built initially by my friend @vipuldelwadia and I and basically does what we need (or needed) it to do. There is some desire to get a command line version out there which just runs as an agent, but other than we have hit our targets.

It's not helped by the fact that neither of us are university students anymore so we have responsibilities and families etc so TVRenamer hacking is very low on list of prioritises!. Also I've moved away from Java many years ago and am firmly in the ruby world and find is very hard to come back to Java!

All that being said, we are both invested in the application and would love to see improvements and enhancements.

I'm glad that you got it going without Eclipse. The IDE of choice seems to be IntelliJ these days which Im told is much faster and lighter than Eclipse. I'm using to using Sublime Text so everything feels very heavy-weight to me!

Your multiple selection sounds a nice idea. Something simple without any large consequences. I don't have any insight into why `SWT.MULTI` doesn't work. I do notice that we bundle SWT version `v4.3` but the latest stable version is `v4.5` so that would be my first port of call! If you do update SWT make sure you update for all platforms/architectures though!

I'll close this 'issue' as it's not a bug or feature request but feel free to be keep replying

Dave

**Closed by daveharris** 2016-09-06 00:37 UTC

**Comment by johnv02139** [comment] 2016-09-06 01:41
Yeah, I've used Android Studio, which is basically IntelliJ, and found it decent.  But I still do most everything in Emacs, honestly.

There was an issue here, which you resolved by pointing me to the Wiki.  :)  I think I will open a new issue to talk about the selection.

**Comment by johnv02139** [comment] 2016-09-23 18:34
Hi, no idea if you've been seeing anything I've been doing in my fork.  As I said, I wanted to learn about tooling and github and all that stuff.  So, a lot of what I've been doing has not really been about making the end-user experience better, but just about developing a project.

In particular, I've been very careful to try to maintain my commits in discrete, mergeable chunks.  If you want to take a look at any of them, and pick and choose, I'd be willing to try to re-order them or whatever makes it easiest to merge them.

However, both due to my divergent interests and your lack of time to devote to it, I'm thinking of converting my work into a new, top-level project.  What would you think of that?

Thanks,
John
